site_name: Selendra Docs
site_description: The Selendra knowledge base
site_author: 'Selendra'
site_url: https://docs.selendra.org

# Navigation  
nav:
 - Home: index.md
 - Basic:
   - Getting Started: basic/getting-started.md
   - Create an Account: basic/getting-started.md
   - Wallet and Balance: basic/getting-started.md
   - Send SEL: basic/getting-started.md
 - Maintain:
   - Set Up a validator: Maintain/guides-how-to-validate-selendra.md
   - Set Up a Full Node: Maintain/guides-how-to-validate-selendra.md
 - Smart Contracts:
   - Deploy a WASM Contract: Maintain/guides-how-to-validate-selendra.md

# Configuration for the Material theme
theme:
  name: material
  favicon: images/sel.ico
  logo: assets/sel.png
  icon:
    repo: fontawesome/brands/github-square
  palette:
    scheme: slate
    primary: white
  font:
    text: 'PT Sans'
    code: 'Ubuntu Mono'
  feature:
    tabs: false
extra:
  social:
    - icon: fontawesome/brands/twitter
      link: https://twitter.com/selendraio
    - icon: fontawesome/brands/telegram
      link: https://t.me/selendra_sel
    - icon: fontawesome/brands/github
      link: https://github.com/selendra
    - icon: fontawesome/brands/medium
      link: https://medium.com/selendra 
    - icon: fontawesome/brands/linkedin
      link: https://www.linkedin.com/company/selendra
repo_url: https://github.com/selendra/selendra-docs
repo_name: selendra/selendra-docs
edit_uri: ""
footer:
  logo: 'assets/sel.png'



      